<?php

return [
    [
        "partie" => "Introduction au cinéma",
        "chapitre" => "Le procédé cinématographique",
        "description" => "Comment fait une image pour bouger ? Quelle est la différence entre le court métrage et le long métrage ? Découvre le procédé cinématographique",
        "duration" => "5 minutes 17",
        "emplacement_maquette" => "Introduction au cinéma",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/01+-+(Re)D%C3%A9couverte/(Re)d%C3%A9couverte+du+cin%C3%A9ma/Video_(Re)De%CC%81couverteducinema_V1_19082022.mp4",
        "video_steps" => [
            "00'28" => "Comment fait une image pour bouger ?",
            "02'05" => "Fabrique ton Flip book",
            "02'49" => "L'animation d'objet en volume",
            "03'42" => "Réalise ton film d'animation",
        ],
        "doc_recap" => "",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non",
        "commentaire" => "",
    ],
    [
        "partie" => "Écris ton Histoire",
        "chapitre" => "Choisis ta thématique",
        "description" => "Tu veux trouver une idée de film ? Trouver ta thématique t'aidera à le faire.",
        "action_message" => "Écris ta thématique dans ACTION !",
        "action_title"   => "La thématique",
        "action_help"    => "La thématique est le sujet du film de quoi il va parler",
        "video_steps" => [
            "00'10" => "La thématique",
            "00'26" => "Qu'est ce que la thématique?",
            "00'55" => "Comment trouver sa thématique",
            "01'30" => "Alors où trouver son idée?",
            "02'58" => "J'ai mon idée et après?"
        ],
        "duration" => "4 minutes 10",
        "emplacement_maquette" => "1 - 1 - Choisis ta thématique",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/2+-+Fiction+-+La+the%CC%81matique-+VF.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/Re%CC%81cap+Choisis+ta+the%CC%81matique+webApp+070322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => [
            "Biodiversité" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/Boi%CC%82teAIde%CC%81es+the%CC%81matique+biodiversite%CC%81+webApp.pdf",
            "L'école"  => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/Boi%CC%82teAIde%CC%81es+the%CC%81matique+e%CC%81cole+webApp.pdf",
            "Egalité Fille-Garçon"  => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/Boi%CC%82teAIde%CC%81es+the%CC%81matique+e%CC%81galite%CC%81+webApp.pdf",
            "Harcèlement"  => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/Boi%CC%82teAIde%CC%81es+the%CC%81matique+harce%CC%80lement+webApp.pdf"
        ],
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/Re%CC%81capitulatif+du+chapitre+-+Choisis+ta+the%CC%81matique.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => [
            "Thématique à complèter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/01+-+Choisis+ta+the%CC%81matique/Le+film+de+fiction+-+La+the%CC%81matique.pdf",
        ],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton Histoire",
        "chapitre" => "Le pitch",
        "duration" => "1 minute 58",
        "description" => "C'est quoi un pitch ? Comment pitcher ? C'est ici",
        "action_message" => "Écris ton pitch dans ACTION !",
        "action_help"    => "Le pitch est une phrase simple et courte qui resume l'idée principale du film",
        "video_steps" => [
            "00'12" => "Le pitch c'est quoi ?",
            "00'53" => "Comment pitcher ?",
        ],
        "emplacement_maquette" => "1 - 2 Le Pitch",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/02+-+Pitch/3+-+Fiction+-+LE+PITCH+-+VF.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/02+-+Pitch/Re%CC%81cap+Pitch+webApp+070322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => [
            "Choses à faire - Pitch réussi !" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/02+-+Pitch/To+do+list+pitch+re%CC%81ussi+webApp.pdf"
        ],
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/02+-+Pitch/Le+chapitre+par+e%CC%81crit+-+Pitch.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => [
            "Pitch à complèter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/02+-+Pitch/Le+film+de+fiction+-+Le+Pitch.pdf"
        ],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton Histoire",
        "chapitre" => "Le schéma narratif",
        "duration" => "4 minutes 04 ",
        "emplacement_maquette" => "1 - 3 Le schéma narratif",
        "description" => "Alors t'as choisi ta thématique, t'as fini de pitcher maintenant passons aux choses sérieuses, passons au schéma narratif!",
        "action_message" => "Écris ton schema narratif dans ACTION !",
        "action_help"    => "le schéma narratif est composé de la situation initiale, de l'élément perturbateur, des péripéties, de l'élément de résolution finale. Constitué de 5 étapes, il permet d'avoir une histoire organisée que tout le monde comprend.",
        "video_steps" => [
            "00:40" => "Qu’est-ce que le schéma narratif ? ",
            "01:00" => "La situation initiale",
            "01:18" => "L’élément perturbateur",
            "01:45" => "Les péripéties",
            "02:36" => "Élément de résolution",
            "03:04" => "La situation finale",
            "03:29" => "Quelques conseils pour écrire un bon schéma narratif",
        ],
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/3+-+Le+sch%C3%A9ma+narratif/4+-+Fiction+-+LE+SCHE%CC%81MA+NARRATIF+-+VF.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/3+-+Le+sch%C3%A9ma+narratif/Re%CC%81cap+Sche%CC%81ma+narratif+webApp.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/3+-+Le+sch%C3%A9ma+narratif/Le+chapitre+par+e%CC%81crit+-+Le+sche%CC%81ma+narratif.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => [
            "Schéma narratif à complèter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/3+-+Le+sch%C3%A9ma+narratif/Sche%CC%81ma+narratif+vierge.pdf"
        ],
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton Histoire",
        "chapitre" => "Le synopsis",
        "duration" => "2 minutes 59",
        "emplacement_maquette" => "1 - 4 Le synopsis",
        "description" => "Non ce n'est pas encore le moment d'écrire ton scénario, avant c'est le synopsis",
        "action_message" => "Écris ton synopsis dans ACTION !",
        "action_help"    => "Le synopsis est le résumé de l'histoire en quelques lignes",
        "video_steps" => [
            "00:29" => "Qu’est-ce qu’un synopsis ?",
            "01:04" => "Comment écrire le Synopsis de son Film ?",
            "02:10" => "Quelques conseils pour écrire le synopsis",
        ],
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/04+-+Le+synopsis/5+-+Fiction+-+LE+SYNOPSIS.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/04+-+Le+synopsis/Re%CC%81cap+E%CC%81cris+ton+synopsis+webApp.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/04+-+Le+synopsis/Le+synopsis+-+Le+chapitre+par+e%CC%81crit.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => [
            "Synopsis à complèter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/04+-+Le+synopsis/Le+film+de+fiction+-+Le+synopsis.pdf"
        ],
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton Histoire",
        "chapitre" => "Le traitement",
        "duration" => "3 minutes 17",
        "emplacement_maquette" => "1 - 5 Le traitement",
        "action_help"    => "Le traitement est la forme très développée du synopsis",
        "description" => "Le traitement est la forme très développée du synopsis. C'est un document assez long pouvant atteindre une vingtaine de pages voir plus si tu veux te lancer dans un film très long.",
        "video_steps" => [
            "00:17" => "Le Traitement, qu’est-ce que c’est ?",
            "00:53" => "Comment écrire un traitement ?",
            "02:10" => "Le traitement, pourquoi est-il si important ?",
        ],
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/05+-+Le+traitement/6+-+Fiction+-+LE+TRAITEMENT.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/05+-+Le+traitement/Re%CC%81cap'+Le+traitement_050722.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/05+-+Le+traitement/Le+chapitre+par+e%CC%81crit+-+Le+traitement.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => [
            "Traitement à complèter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/05+-+Le+traitement/A+comple%CC%81ter+_+Le+film+de+fiction+-+Le+traitement.pdf"
        ],
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton Histoire",
        "chapitre" => "Le récap'",
        "duration" => "0 minute 57",
        "description" => "C'est le moment! L'écriture de ton scénario!",
        "emplacement_maquette" => "1 - 6 Le recap’",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/06+-+Le+re%CC%81cap'/7+-+Fiction+-+ECRIS+TON+HISTOIRE+RE%CC%81CAP.mp4",
        "video_steps" => [],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/06+-+Le+re%CC%81cap'/Le+Re%CC%81cap'+-+Ecris+ton+histoire+070322.pdf",
        "fiche_recap_des_chapitres" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/06+-+Le+re%CC%81cap'/Le+Re%CC%81cap'+Le+re%CC%81cap+-+Ecris+ton+histoire_050722.pdf",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/06+-+Le+re%CC%81cap'/Le+cours+par+e%CC%81crit+-+Le+re%CC%81cap+_E%CC%81cris+ton+histoire_.pdf",
        "tous_les_chapitres_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/02+-+Ecris+ton+histoire/06+-+Le+re%CC%81cap'/Le+chap+par+e%CC%81crit+-+tous+les+chap_E%CC%81cris+ton+histoire_.pdf",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton scénario comme un.e pro",
        "chapitre" => "Les séquences",
        "duration" => "6 minutes 11",
        "name" => "Les séquences",
        "description" => "La première fonction du scénario est de prśenter le film sous la forme d'un découpage séquentiel",
        "action_message" => "Écris tes séquences dans ACTION !",
        "video_steps" => [
            "00:17" => "Qu’est-ce qu’une séquence ?",
            "00:32" => "Comment présenter une séquence ?",
            "02:12" => "Le contenu d’une séquence",
            "04:02" => "Quelques conseils pour écrire tes séquences",
        ],
        "emplacement_maquette" => "2 - 1 - Les séquences",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/01+-+Les+se%CC%81quences/8+-+Fiction+-+LES+SE%CC%81QUENCES.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/01+-+Les+se%CC%81quences/Les+Se%CC%81quences.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/01+-+Les+se%CC%81quences/Le+chapitre+par+e%CC%81crit+-+Les+se%CC%81quences.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton scénario comme un.e pro",
        "chapitre" => "Les dialogues",
        "duration" => "4 minutes 01",
        "name" => "Les dialogues",
        "description" => "Les dialogues sont les mots, les phrases, les expressions, bref tout ce que va dire ton personnage",
        "action_message" => "Écris tes dialogues dans ACTION !",
        "video_steps" => [
            "00:50" => "Qu’est-ce qu’un dialogue ?",
            "01:16" => "Mise en page d’un dialogue",
            "01:38" => "Les didascalies, un outil pour guider tes acteurs",
            "02:21" => "Écrire les dialogues, un calvaire ?",
        ],
        "emplacement_maquette" => "2 - 2 - Les dialogues",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/02+-+Les+dialogues/9+-+Fiction+-+LES+DIALOGUES.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/02+-+Les+dialogues/Re%CC%81cap'+-+Dialogues+070322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/02+-+Les+dialogues/Le+chap+par+e%CC%81crit+-+les+dialogues.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton scénario comme un.e pro",
        "chapitre" => "La musique",
        "duration" => "3 minutes 12",
        "name" => "La musique",
        "description" => "Dans certains films la musique peut parfois prendre une très grande place dans l'écriture du scénario.",
        "action_message" => "Écris dans ACTION !",
        "video_steps" => [
            "00:23" => "La musique diégétique",
            "01:49" => "La mise en page de la musique diégétique",
            "02:08" => "La musique extradiégétique",
            "02:35" => "La mise en page de la musique extradiégétique",

        ],
        "emplacement_maquette" => "2 - 3 - La musique",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/03+-+La+musique/Le+sce%CC%81nario+-+LA+MUSIQUE.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/03+-+La+musique/La+Musique+080322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/03+-+La+musique/Le+chap+par+e%CC%81crit+-+La+musique.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Écris ton scénario comme un.e pro",
        "chapitre" => "Le récap'",
        "duration" => "2 minutes 54",
        "name" => "Le récap'",
        "description" => "Tu es encore là? Si tu as survécu à cette étape et que tu as suivi toutes les étapes, il faut que tu fasses attention à certaines choses.",
        "action_message" => "Écris ton scénario dans ACTION !",
        "video_steps" => [
            "00:10" => "Le scénario, juste le scénario",
            "00:50" => "Trucs et astuces pour un scénario réussi",
            "02:03" => "Récap’ de la partie « Le scénario » et présentation de la partie « Prépare ton tournage »",
        ],
        "emplacement_maquette" => "2 - 4 - Le récap",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/04+-+Le+re%CC%81cap'/Le+sce%CC%81nario+-+Le+re%CC%81cap'.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/04+-+Le+re%CC%81cap'/Le_sce%CC%81nario_Le+Re%CC%81cap'+080322.pdf",
        "fiche_recap_des_chapitres" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/04+-+Le+re%CC%81cap'/Tous+les+chap+par+e%CC%81crit+-+Ecris+ton+sce%CC%81nario.pdf",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/04+-+Le+re%CC%81cap'/Le+chap+par+e%CC%81crit+-+Le+re%CC%81cap.pdf",
        "tous_les_chapitres_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/03+-+Ecris+ton+sce%CC%81nario/04+-+Le+re%CC%81cap'/Tous+les+chap+par+e%CC%81crit+-+Ecris+ton+sce%CC%81nario.pdf",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "L’échelle des plans",
        "duration" => "10 minutes 13",
        "name" => "L'échelle des plans",
        "description" => "Si en tant que réalisateur tu n'es pas forcément obligé de savoir manipuler une caméra pour réaliser
                ton film, ça ne veut pas dire que tu n'as pas besoin de connaissance technique. Parmi les savoirs importants qu'un réalisateur
                doit connaitre, il y a les plans de l'échelles des plans",
        "action_message" => "Écris ton découpage technique dans ACTION !",
        "video_steps" => [
            "01:12" => "C’est quoi un plan ?",
            "02:00" => "Les plans larges",
            "02:42" => "Le plan général",
            "03:18" => "Le plan d’ensemble",
            "03:42" => "Les plans moyens",
            "04:02" => "Le plan moyen ou plan pied",
            "04:20" => "Le plan italien",
            "04:44" => "Le plan américain",
            "05:00" => "Le plan rapproché taille",
            "05:30" => "Le plan rapproché poitrine",
            "05:56" => "Le plan rapproché épaule",
            "06:17" => "Les gros plans",
            "06:57" => "Le gros plan",
            "07:15" => "Le très gros plan",
            "07:40" => "Le plan d’insert",
            "08:00" => "Le champ / contrechamp",
            "08:54" => "Les plans avec amorce",
        ],
        "emplacement_maquette" => "3 - 1 - L’échelle des plans",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/01+-+L%E2%80%99%C3%A9chelle+des+plans/Vide%CC%81o_Echelle+des+plans_VF.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/01+-+L%E2%80%99%C3%A9chelle+des+plans/L'e%CC%81chelle_des_plans_080322.pdf",
        "to_do_list" => [
            "Les échelles de plan" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/01+-+L%E2%80%99%C3%A9chelle+des+plans/Les+diffe%CC%81rentes+e%CC%81chelles+de+plan_080322.pdf"
        ],
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "exemple" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/01+-+L%E2%80%99%C3%A9chelle+des+plans/Les+diffe%CC%81rentes+e%CC%81chelles+de+plan_080322.pdf",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/01+-+L%E2%80%99%C3%A9chelle+des+plans/Le+chap+par+e%CC%81crit+-+L%E2%80%99e%CC%81chelle+des+plans.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "L’angle de la caméra",
        "duration" => "04 minutes 09",
        "name" => "L'angle de la caméra",
        "description" => "Au cinéma connaitre l'angle de ta caméra est aussi important que l'échelle que tu vas utiliser pour filmer",
        "action_message" => "Écris ton découpage technique dans ACTION !",
        "emplacement_maquette" => "3 - 2 - L’angle de la caméra",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/02+-+L%E2%80%99angle+de+la+cam%C3%A9ra/Video_angledecamera_V3.mp4",
        "video_steps" => [
            "00:10" => "Positionner sa caméra",
            "00:40" => "Le plan de face",
            "01:00" => "La plongée",
            "02:10" => "La contre-plongée",
            "02:59" => "La plongée et contre plongée - Une astuce à utiliser avec modération",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/02+-+L%E2%80%99angle+de+la+cam%C3%A9ra/Les+angles+de+came%CC%81ra_080322.pdf",
        "to_do_list" => [
            "L'angle de la caméra" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/02+-+L%E2%80%99angle+de+la+cam%C3%A9ra/L'angle_de_la_came%CC%81ra_positions_080322.pdf"
        ],
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "exemple" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/02+-+L%E2%80%99angle+de+la+cam%C3%A9ra/L'angle_de_la_came%CC%81ra_positions_080322.pdf",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/02+-+L%E2%80%99angle+de+la+cam%C3%A9ra/Le+chapitre+par+e%CC%81crit+-+L'angle+de+la+came%CC%81ra.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "La stabilité de la caméra",
        "duration" => "10 minutes 20",
        "name" => "La stabilité de la caméra",
        "description" => "C'est une règle, lorsque l'on film, l'image doit rester satble. Cette règle peut être exceptionnellement contredite ou modifié mais pas ignoré",
        "action_message" => "Écris ton découpage technique dans ACTION !",
        "emplacement_maquette" => "3 - 3 - La stabilité de la caméra",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/03+-+La+stabilit%C3%A9+de+la+cam%C3%A9ra/Video_stabilitecamera_V3.mp4",
        "video_steps" => [
            "00:10" => "La stabilité de l’image, une règle importante au cinéma et à la télévision",
            "01:31" => "Pourquoi c’est important ?",
            "02:25" => "La caméra portée",
            "03:48" => "La caméra portée - Les positions à adopter",
            "05:27" => "Le stabilisateur d’image",
            "06:21" => "Le trépied",
            "08:14" => "Quelques conseils pour utiliser ton trépied correctement",
            "09:00" => "Quand un simple monopode suffit",
            "09:40" => "La stabilité, le maître mot d’une image réussie",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/03+-+La+stabilit%C3%A9+de+la+cam%C3%A9ra/Re%CC%81cap+-+La+Stabilite%CC%81_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => [
            "La stabilité de la caméra " => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/03+-+La+stabilit%C3%A9+de+la+cam%C3%A9ra/Stabilite%CC%81+de+la+came%CC%81ra+noir+%26+blanc.pdf"
        ],
        "exemple" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/03+-+La+stabilit%C3%A9+de+la+cam%C3%A9ra/Stabilite%CC%81+de+la+came%CC%81ra+noir+%26+blanc.pdf",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/03+-+La+stabilit%C3%A9+de+la+cam%C3%A9ra/Le+chapitre+par+e%CC%81crit+-+La+stabilite%CC%81+de+la+came%CC%81ra.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Les mouvements de la caméra",
        "duration" => "10 minutes 08",
        "name" => "Les mouvements de la caméra",
        "description" => "Tout comme l'échelle des plans, l'utilisation du mouvement doit être justifié par une volonté narrative précise",
        "emplacement_maquette" => "3 - 4 - Les mouvements de la caméra",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/04+-+Les+mouvements+de+la+cam%C3%A9ra/Video_mouvementcamera_v2.mp4",
        "action_message" => "Écris ton découpage technique dans ACTION !",
        "video_steps" => [
            "00:10" => "Les différents mouvements de la caméra",
            "00:43" => "Qu’est-ce qu’un mouvement de caméra ?",
            "01:05" => "Le travelling",
            "01:51" => "Le panoramique",
            "02:48" => "Le zoom (le travelling optique)",
            "04:49" => "Le travelling compensé ou transtrav",
            "05:18" => "L’exception du plan fixe",
            "05:54" => "Le plan séquence",
            "07:08" => "Mes conseils pour exécuter un mouvement à la perfection",
            "09:28" => "Comment choisir ses plans et ses mouvements de caméra",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/04+-+Les+mouvements+de+la+cam%C3%A9ra/Re%CC%81cap_Les_mouvements_de_la_came%CC%81ra_080322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => ["Les mouvements de la caméra" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/04+-+Les+mouvements+de+la+cam%C3%A9ra/Mouvements+de+la+came%CC%81ra+Noir+%26+Blanc+-+illustrations.pdf"],
        "exemple" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/04+-+Les+mouvements+de+la+cam%C3%A9ra/Mouvements+de+la+came%CC%81ra+Noir+%26+Blanc+-+illustrations.pdf",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/04+-+Les+mouvements+de+la+cam%C3%A9ra/Le+chapitre+par+e%CC%81crit+-+Les+mouvements+de+la+came%CC%81ra.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Les différentes manières de réaliser un travelling",
        "duration" => "4 minutes 21",
        "name" => "Les différentes manières de réaliser un travelling",
        "description" => "Tout comme l'échelle des plans, l'utilisation du mouvement doit être justifié par une volonté narrative précise.",
        "action_message" => "Écris ton découpage technique dans ACTION !",
        "emplacement_maquette" => "3 - 5 - Les mouvements de la caméra - Les différentes manières de réaliser un travelling",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/05+-+Les+diffe%CC%81rentes+manie%CC%80re+de+re%CC%81aliser+un+travelling/Video_realisertravelling_V2.mp4",
        "video_steps" => [
            "00:21" => "Marcher avec l’appareil à la main",
            "01:49" => "Le trépied attaché à des roues",
            "02:34" => "Le fauteuil roulant",
            "03:27" => "Les véhicules",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/05+-+Les+diffe%CC%81rentes+manie%CC%80re+de+re%CC%81aliser+un+travelling/Les_diffe%CC%81rentes_manie%CC%80res_travelling_080322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/05+-+Les+diffe%CC%81rentes+manie%CC%80re+de+re%CC%81aliser+un+travelling/Le+chapitre+par+e%CC%81crit+-+Les+mouvements+de+la+came%CC%81ra+-+Les+diffe%CC%81rentes+manie%CC%80re+de+re%CC%81aliser+un+travelling.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Le découpage technique",
        "duration" => "6 minutes 53",
        "name" => "Le découpage technique",
        "description" => "Une des dernières étapes de préparation du réalisateur avant le tournage, le découpage technique te permettra de mettre à l'ecrit tpit ce que tu souhaites dans ton film ou ta vidéo",
        "action_message" => "Écris ton découpage technique dans ACTION !",
        "video_steps" => [
            "00:31" =>  "C’est quoi un découpage technique ?",
            "01:48" =>  "Comment remplir la feuille de découpage ?",
            "02:41" =>  "Comment remplir la partie image ?",
            "03:39" =>  "Comment remplir la partie son ?",
            "04:43" =>  "Comment remplir la partie raccord ?",
            "06:12" =>  "Le découpage technique, pourquoi est-il si important ?",
        ],
        "emplacement_maquette" => "3 - 6 - Le découpage technique",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/06+-+Le+de%CC%81coupage+technique/Video_de%CC%81coupage_V3.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/06+-+Le+de%CC%81coupage+technique/Re%CC%81cap_de%CC%81coupage_technique_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => [],
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/06+-+Le+de%CC%81coupage+technique/Le+chapitre+par+e%CC%81crit+-+Le+de%CC%81coupage+technique.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => [" Découpage technique à compléter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/06+-+Le+de%CC%81coupage+technique/Document+a%CC%80+comple%CC%81ter+_+de%CC%81coupage+technique.pdf"],
        "integration" => "Non'",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Le storyboard",
        "duration" => "2 minutes 30",
        "name" => "Le storyboard",
        "description" => "Il s'agit du découpage dessiné plan par plan, avec parfois plusieurs dessis par plan s'il s'agit d'un mouvement de caméra",
        "video_steps" => [
            "00:27" => "Qu’est ce que le storyboard ?",
            "01:26" => "Comment le réaliser ?",
            "01:59" => "Le storyboard ? Un outil indispensable ?",
        ],
        "action_message" => "Remplis ton storyboard dans ACTION !",
        "emplacement_maquette" => "3 - 7 - Le storyboard",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/07+-+Le+storyboard/Video_storyboard_V3.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/07+-+Le+storyboard/Re%CC%81cap'+_+Le+Storyboard.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/07+-+Le+storyboard/Le+chapitre+par+e%CC%81crit+-+Le+storyboard.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => ["Storyboard à compléter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/07+-+Le+storyboard/a%CC%80+completer_Le+storyboard.pdf"],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Le récap' Choisis tes plans",
        "duration" => "3 minutes 41",
        "description" => "Bien préparer ses plans, c'est important",
        "action_message" => "Prépare ton tournage dans ACTION !",
        "video_steps" => [
            "00:10" => "Bien préparer ses plans, c’est important",
            "00:50" => "Les différentes échelles des plans",
            "01:49" => "Les différents mouvement de caméra",
            "02:36" => "Bien réaliser son découpage technique",
            "03:02" => "Le storyboard",
        ],
        "emplacement_maquette" => "3 - 8 - Choisis tes plans",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/08+-+Le+re%CC%81cap%E2%80%99+Choisis+tes+plans/Video_recaptournage_V1.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/08+-+Le+re%CC%81cap%E2%80%99+Choisis+tes+plans/Le+Re%CC%81cap%E2%80%99+Choisis+tes+plans_080322_C.pdf",
        "fiche_recap_des_chapitres" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/08+-+Le+re%CC%81cap%E2%80%99+Choisis+tes+plans/Le+Re%CC%81cap%E2%80%99+Les+re%CC%81cap+Choisis+tes+plans_080322_C.pdf",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/08+-+Le+re%CC%81cap%E2%80%99+Choisis+tes+plans/Le+chapitre+par+e%CC%81crit+-+Le+re%CC%81cap%E2%80%99+Choisis+tes+plans.pdf",
        "tous_les_chapitres_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/08+-+Le+re%CC%81cap%E2%80%99+Choisis+tes+plans/Le+chapitre+par+e%CC%81crit+-+Le+re%CC%81cap%E2%80%99+Choisis+tes+plans+all.pdf",
        "doc_a_completer" => "",
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "La lumière",
        "duration" => "5 minutes 58",
        "name" => "La lumière",
        "description" => "Parfois sous estimé lorsqu'on prépare un tournage, la lumière est pourtant un élément très important puisqu'il permet au film de donner un sesns émotionnel à l'image, d'avoir une ambiance, une symphonie de couleur, de faisceaux lumineux",
        "video_steps" => [
            "00:10" => "La lumière au cinéma ou à la télévision",
            "00:42" => "L’éclairage, à quoi ça sert ?",
            "01:21" => "L’importance de la lumière naturelle",
            "​​02:18" => "Les différentes lumières artificielles",
            "03:33" => "L’éclairage en trois points",
            "04:46" => "Quelques conseils pour se perfectionner",
        ],
        "action_message" => "Prépare ton tournage dans ACTION !",
        "emplacement_maquette" => "3 - 10 - La lumière",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/10+-+La+lumie%CC%80re/Video_lumie%CC%80re_V2.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/10+-+La+lumie%CC%80re/Re%CC%81cap+'+-+La+lumie%CC%80re_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => [
            "Les différents types de lumières" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/10+-+La+lumie%CC%80re/LES+DIFFE%CC%81RENTS+TYPES+DE+LUMIE%CC%80RES+noir+%26+blanc+-+illustrations.pdf",
            "7 façons d’éclairer un sujet" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/10+-+La+lumie%CC%80re/7+FAC%CC%A7ONS+D'E%CC%81CLAIRER+UN+SUJET+noir+et+blanc+-+illustrations.pdf",
        ],
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/10+-+La+lumie%CC%80re/Le+chapitre+par+e%CC%81crit+-+La+lumie%CC%80re.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Le son",
        "duration" => "03 minutes 06",
        "emplacement_maquette" => "3 - 11 bis - Le son",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/Le+son/Video_son_v1.mp4",
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/Le+son/Re%CC%81cap+'+-+Le+son+080322_C.pdf",
        "action_message" => "Prépare ton tournage dans ACTION !",
        "description" => "Parfois oublié mais très important, le son est un indispensable.",
        "video_steps" => [
            "00:10" => "Le son",
            "00:24" => "Le microphone dynamique",
            "00:57" => "Le micro statique",
            "​01:32" => "Le micro canon",
            "01:58" => "Le micro cravate",
            "02:27" => "Choisir son micro, pourquoi c’est important ?",
        ],
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/Le+son/Le+chap+par+e%CC%81crit+-+Le+son.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "La feuille de script",
        "duration" => "3 minutes 42",
        "name" => "La feuille de script",
        "description" => "Ce document permet de donner des indications sur les prises à conserver pour le montage",
        "action_message" => "La feuille de script dans ACTION !",
        "emplacement_maquette" => "3 - 9 - La feuille de script",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/09+-+La+feuille+de+script/Video_feuilledescript_v2.mp4",
        "video_steps" => [
            "00:10" => "C’est quoi une feuille de script ?",
            "00:37" => "Bien savoir remplir sa feuille de script",
            "02:39" => "Pourquoi remplir sa feuille de script",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/09+-+La+feuille+de+script/Re%CC%81cap'+-+La+feuille+de+script_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/09+-+La+feuille+de+script/Le+chapitre+par+e%CC%81crit+-+La+feuille+de+script.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => [
            "Feuille de script à completer" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/09+-+La+feuille+de+script/a%CC%80+comple%CC%81ter+-+Feuille+de+script.pdf"
        ],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Trouver son équipe technique",
        "duration" => "10 minutes 40",
        "emplacement_maquette" => "3 - 11 - Trouver son équipe technique",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/11+-+Trouver+son+e%CC%81quipe+technique/Video_equipetechnique_V4_15072022.mp4",
        "video_steps" => [
            "00:27" => "Bien choisir, pourquoi c’est si important ?",
            "01:10" => "Les différents postes",
            "01:19" => "Le•La producteur•trice",
            "02:23" => "Le•La réalisateur•trice",
            "02:42" => "L’assistant•e réalisateur•trice",
            "03:08" => "Le•La scripte",
            "03:21" => "Le•La régisseur•euse",
            "03:54" => "Le•La chef•fe opérateur•rice",
            "04:15" => "Le•La cadreuse",
            "04:36" => "Le•La chef•fe électricien•ne",
            "04:58" => "L’électricien•ne",
            "05:11" => "Le•La machiniste",
            "05:34" => "Le•La chef•fe opérateur•rice son",
            "05:45" => "Le•La perchiste",
            "06:04" => "Le•La costumier.ière",
            "06:23" => "Le•La maquilleur•euse",
            "06:37" => "Le•La coiffeur•euse",
            "06:57" => "Le•La chef•fe décorateur•rice",
            "07:10" => "L'accessoiriste",
            "07:30" => "Où trouver son équipe technique",
            "09:05" => "Comment choisir les membres de son équipe",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/11+-+Trouver+son+e%CC%81quipe+technique/Re%CC%81cap+'+-+Trouver+son+e%CC%81quipe+technique_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/11+-+Trouver+son+e%CC%81quipe+technique/Le+chapitre+par+e%CC%81crit+-+Trouver+son+e%CC%81quipe+technique.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Trouver ses comédie•ne•s",
        "duration" => "11 minutes 39",
        "description" => "Découvre les différents types d'interprétation et quelques conseils pour dénicher les meilleur•e•s comédien•ne•s..",
        "emplacement_maquette" => "3 - 12 - Trouver ses comédiens",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/12+-+Trouver+ses+come%CC%81diens/Video_comediens_V3_19072022.mp4",
        "video_steps" => [
            "00:27" => "Bien choisir, pourquoi c’est si important ?",
            "01:02" => "Les différents types d’interprétation",
            "01:23" => "Le premier rôle",
            "01:56" => "Le second rôle",
            "02:24" => "La silhouette parlante",
            "02:39" => "La silhouette",
            "02:53" => "Le•La figurant•e",
            "03:08" => "La doublure lumière/cadrage/texte",
            "03:22" => "La doublure image",
            "03:44" => "Le•La cascadeur•euse",
            "03:58" => "La voix off",
            "04:30" => "Le•La doubleur•euse",
            "04:54" => "Le•La directeur•rice de casting",
            "05:51" => "Où trouver ses comédien•ne•s ?",
            "07:04" => "Comment organiser un casting ?",
            "09:27" => "Comment choisir la bonne personne ?",
            "10:42" => "Je veux jouer dans mon film ! C’est possible ?",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/12+-+Trouver+ses+come%CC%81diens/Re%CC%81cap+'+Trouver+ses+come%CC%81diens_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/12+-+Trouver+ses+come%CC%81diens/Le+chapitre+par+e%CC%81crit+-+Trouver+ses+come%CC%81diens.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Liste technique et artistique",
        "duration" => "02 minutes 08",
        "name" => "Liste technique et artistique",
        "description" => "Tu es surement impatient de trourné mais sache qu'il a encore quelques documents à préparer avec de dire le fameux <<Action>>.
                Parmi ces documents, tu trouveras la liste technique et artistique
                ",
        "emplacement_maquette" => "3 - 13 - Liste technique et artistique",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/13+-+Liste+technique+et+artistique/Video_listetechnique_V2.mp4",
        "video_steps" => [
            "00:24" => "En quoi ça consiste ?",
            "00:40" => "Comment la remplir ?",
            "00:50" => "Une liste sous-estimée mais très utile",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/13+-+Liste+technique+et+artistique/Re%CC%81cap'+-+Liste+technique+et+artistique_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/13+-+Liste+technique+et+artistique/Le+chapitre+par+e%CC%81crit+-+Liste+technique+et+artistique.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => ["Liste technique et artistique à compléter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/13+-+Liste+technique+et+artistique/a%CC%80+comple%CC%81ter+-+La+liste+technique+et+artistique.pdf"],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "La liste des acteurs/actrices",
        "duration" => "1 minute 23",
        "name" => "La liste des actrices/acteurs",
        "description" => "Comme son nom l'indique la liste des actrices et des acteurs est nécessaire pour bien préparer ton tournage",
        "emplacement_maquette" => "3 - 14 - La liste des acteurs/actrices",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/14+-+La+liste+des+acteurs+-+actrices/Video_listeacteurs_V2_15072022.mp4",
        "video_steps" => [
            "00:19" => "En quoi ça consiste ?",
            "00:36" => "Comment la remplir ?",
            "00:46" => "Pourquoi c’est important ?",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/14+-+La+liste+des+acteurs+-+actrices/Re%CC%81cap+'+-+La+liste+des+acteurs+et+actrices.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/14+-+La+liste+des+acteurs+-+actrices/Chapitre+par+e%CC%81crit+-+La+liste+acteur_actrice.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => ["La liste des acteurs/actrices à compléter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/14+-+La+liste+des+acteurs+-+actrices/a%CC%80+comple%CC%81ter+-+Liste+des+acteurs_actrices.pdf"],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "La feuille de dépouillement des personnages",
        "duration" => "02 minutes 49",
        "name" => "La feuille de dépouillement des personnages",
        "description" => "Document indispensable pour ton tournage",
        "emplacement_maquette" => "3 - 15 - La feuille de dépouillement des personnages",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/15+-+La+feuille+de+de%CC%81pouillement+des+personnages/Video_depouillementperso_V2_12072022.mp4",
        "video_steps" => [
            "00:23" => "En quoi ça consiste ?",
            "00:43" => "Comment la remplir ?",
            "01:41" => "Pourquoi c’est important ?",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/15+-+La+feuille+de+de%CC%81pouillement+des+personnages/Re%CC%81cap'+-+La+feuille+de+de%CC%81pouillement+des+personnages.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/15+-+La+feuille+de+de%CC%81pouillement+des+personnages/Le+chapitre+par+e%CC%81crit+-+La+feuille+de+de%CC%81pouillement+des+personnages.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => ["La feuille de dépouillement des personnages à compléter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/15+-+La+feuille+de+de%CC%81pouillement+des+personnages/a%CC%80+comple%CC%81ter+-+De%CC%81pouillement+personnage.pdf"],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "La feuille de dépouillement générale",
        "duration" => "03 minutes 06",
        "name" => "La feuille de dépouillement générale",
        "description" => "Document indispensable pour ton tournage",
        "emplacement_maquette" => "3 - 16 - La feuille de dépouillement générale",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/16+-+La+feuille+de+de%CC%81pouillement+ge%CC%81ne%CC%81rale/Video_depouillementgnrl_V2_12072022.mp4",
        "video_steps" => [
            "00:21" => "Qu’est-ce que c’est ?",
            "00:51" => "Comment la remplir ?",
            "02:33" => "Pourquoi c’est important ?",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/16+-+La+feuille+de+de%CC%81pouillement+ge%CC%81ne%CC%81rale/Re%CC%81cap+'+-+La+feuille+de+de%CC%81pouillement+ge%CC%81ne%CC%81ral_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/16+-+La+feuille+de+de%CC%81pouillement+ge%CC%81ne%CC%81rale/Le+chap+par+e%CC%81crit+-+La+feuille+de+de%CC%81pouillement+ge%CC%81ne%CC%81rale.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => ["La feuille de dépouillement générale à compléter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/16+-+La+feuille+de+de%CC%81pouillement+ge%CC%81ne%CC%81rale/a%CC%80+comple%CC%81ter+-+De%CC%81pouillement+ge%CC%81ne%CC%81ral.pdf"],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "La feuille de service",
        "duration" => "05 minutes 00",
        "name" => "La feuille de service",
        "description" => "Document indispensable pour ton tournage",
        "emplacement_maquette" => "3 - 17 - La feuille de service",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/17+-+La+feuille+de+service/Video_feuilleservice_V2_12072022.mp4",
        "video_steps" => [
            "00:20" => "Qu’est-ce que c’est ?",
            "00:51" => "Comment la remplir ?",
            "03:06" => "Pourquoi la remplir ?",
            "03:33" => "Quelques conseils pour bien la remplir.",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/17+-+La+feuille+de+service/La+feuille+de+service_080322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/17+-+La+feuille+de+service/Le+chapitre+par+e%CC%81crit+-+La+feuille+de+service.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => ["La feuille de service à compléter" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/17+-+La+feuille+de+service/a%CC%80+comple%CC%81ter+-+La+feuille+de+service.pdf"],
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Être un.e comédien.ne au top",
        "duration" => "10 minutes 42",
        "description" => "En tant que réalisateur, tu vas devoir veiller à ce que chaque comédien apprenne ses répliques et incarne son rôle à la perfection. ",
        "emplacement_maquette" => "3 - 18 - Être un.e comédien.ne au top",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/E%CC%82tre+un.e+come%CC%81dien.ne+au+top+!/Video_comedientop_V4_29082022.mp4",
        "video_steps" => [
            "00:50" => "Comprendre son personnage",
            "02:01" => "Personnaliser son scénario",
            "03:16" => "Lire et relire ses répliques, à voix haute",
            "04:35" => "Se fixer des objectifs",
            "05:53" => "La clé pour les répliques difficiles",
            "06:50" => "Se lever et trouver son rythme",
            "08:02" => "Se faire aider",
            "08:59" => "S'entraîner partout et tout le temps",
            "09:44" => "L’italienne et l’allemande",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/E%CC%82tre+un.e+come%CC%81dien.ne+au+top+!/E%CC%82tre+un.e+come%CC%81dien.ne+au+top_090322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/E%CC%82tre+un.e+come%CC%81dien.ne+au+top+!/Le+chapitre+par+e%CC%81crit+-+E%CC%82tre+un.e+come%CC%81dien.ne+au+top+!.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "",
        "commentaire" => ""
    ],
    [
        "partie" => "Prépare ton tournage",
        "chapitre" => "Le récap'",
        "duration" => "01 minute 56",
        "emplacement_maquette" => "3 - 19 - Prépare ton tournage - Le récap’",
        "description" => "Tu ne t’attendais sûrement pas à avoir autant de choses à faire avant le tournage, et tu te demandes sûrement si tout ça est vraiment nécessaire ? Et bien figure quoi que oui ! ",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/Le+re%CC%81cap'/Video_recap_V2_29082022.mp4",
        "video_steps" =>  [
            "00:20" => "Est-ce vraiment nécessaire ?",
            "00:56" => "Demander de l’aide",
            "01:19" => "Présentation de la partie \"Tournage\"",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/Le+re%CC%81cap'/Pre%CC%81pare+ton+tournage+le+re%CC%81cap'_090322_C.pdf",
        "fiche_recap_des_chapitres" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+recap'/Les+recap+-+Le+tournage+-+le+re%CC%81cap_090322_C.pdf",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/Le+re%CC%81cap'/Le+chapitre+par+e%CC%81crit+-+Le+re%CC%81cap%E2%80%99.pdf",
        "tous_les_chapitres_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/04+-+Pr%C3%A9pare+ton+tournage/Le+re%CC%81cap'/Tous+les+chap+par+e%CC%81crit+-+Pre%CC%81pare+ton+tournagepdf.pdf",
        "doc_a_completer" => "",
        "integration" => "",
        "commentaire" => ""
    ],
    [
        "partie" => "Le tournage",
        "chapitre" => "Le matériel à avoir",
        "duration" => "04 minutes 49",
        "name" => "Le matériel à avoir",
        "description" => "Les indispensables pour que ton film soit de la meilleure qualité",
        "emplacement_maquette" => "4 - 2 - Le matériel à avoir",
        "action_message" => "Gère ton tournage dans ACTION",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+mate%CC%81riel+a%CC%80+avoir/Video_materiel_V2_15072022.mp4",
        "video_steps" => [
            "00:29" => "Le trépied",
            "00:59" => "Le micro",
            "01:16" => "L'enregistreur",
            "02:26" => "Le casque",
            "02:42" => "La lumière",
            "03:13" => "Les sauvegardes",
            "03:23" => "Les cartes mémoire",
            "03:59" => "Les disques durs",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+mate%CC%81riel+a%CC%80+avoir/Le+mate%CC%81riel+a%CC%80+avoir_090322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+mate%CC%81riel+a%CC%80+avoir/Le+chapitre+par+e%CC%81crit+-+Le+mate%CC%81riel+a%CC%80+avoir.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Le tournage",
        "chapitre" => "Le clap, l'accessoire qu'il faut pour faire un film",
        "duration" => "07 minutes 22",
        "emplacement_maquette" => "",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+clap%2C+l%E2%80%99accessoire+qu%E2%80%99il+faut+pour+faire+un+film/Video_Clap_V1_17082022.mp4",
        "video_steps" => [
            "00:42" => "Le clap, c’est quoi ?",
            "02:05" => "Les informations à renseigner",
            "02:38" => "Les informations de tournage, partie 1",
            "03:18" => "Les informations de tournage, partie 2",
            "04:21" => "Les informations techniques",
            "05:24" => "Comment “claper” ?",
            "05:56" => "Je n’ai pas de clap, comment faire ?",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+clap%2C+l%E2%80%99accessoire+qu%E2%80%99il+faut+pour+faire+un+film/Le+clap%2C+l%E2%80%99accessoire+qu%E2%80%99il+faut+pour+faire+un+film+090322_C.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+clap%2C+l%E2%80%99accessoire+qu%E2%80%99il+faut+pour+faire+un+film/Le+chapitre+par+e%CC%81crit+-+Le+clap%2C+l%E2%80%99accessoire+qu'il+faut+pour+faire+un+film.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "",
        "commentaire" => ""
    ],
    [
        "partie" => "Le tournage",
        "chapitre" => "Ce qu’il faut dire et faire lors du tournage",
        "duration" => "10 minutes 23",
        "name" => "Ce qu'il faut dire et faire lors du tournage",
        "action_message" => "Gère ton tournage dans ACTION",
        "description" => "Tu l’as sûrement vu à la télé ou sur les réseaux sociaux, le clap est un élément utilisé sur les tournages. Objet culte du cinéma, tout le monde voit ce que c’est mais très peu de monde sait à quoi il sert réellement.",
        "emplacement_maquette" => "4 - 2 - Ce qu’il faut dire et faire lors du tournage",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Ce+qu%E2%80%99il+faut+dire+et+faire+lors+du+tournage/Video_direfaire_V3_19072022.mp4",
        "video_steps" => [
            "00:32" => "Le PÀT",
            "00:57" => "La mise en place",
            "01:45" => "La mécanique",
            "02:33" => "La répétition ",
            "03:21" => "La feuille de script",
            "04:10" => "Attention aux faux raccords",
            "04:58" => "Qui dit quoi ?",
            "05:17" => "“Silence !”",
            "05:32" => "“Moteur”",
            "05:50" => "“Moteur demandé”",
            "06:12" => "“Ça tourne au son, ça tourne à l’image”",
            "06:39" => "“30 sur 7, deuxième”",
            "07:17" => "“CLAP !”",
            "07:55" => "“ACTION !”",
            "08:11" => "“COUPEZ !”",
            "08:43" => "“Fin de tournage”",
            "09:20" => "CLAP DE FIN",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Ce+qu%E2%80%99il+faut+dire+et+faire+lors+du+tournage/Ce+qu'il+faut+dire+et+faire+lors+du+tournage_090322.pdf",
        "fiche_recap_des_chapitres" => "",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Ce+qu%E2%80%99il+faut+dire+et+faire+lors+du+tournage/Le+chapitre+par+e%CC%81crit+-+Ce+qu%E2%80%99il+faut+dire+et+faire+lors+du+tournage.pdf",
        "tous_les_chapitres_par_ecrit" => "",
        "doc_a_completer" => "",
        "integration" => "Non",
        "commentaire" => ""
    ],
    [
        "partie" => "Le tournage",
        "chapitre" => "Le récap'",
        "duration" => "01 minute 01",
        "description" => "Tu as terminé ton tournage ?",
        "emplacement_maquette" => "",
        "video" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+recap'/Video_Tournagerecap_V1_17082022.mp4",
        "video_steps" => [
            "00:00" => "Récap' de la partie \"Tournage\"",
            "00:00 " => "Présentation de la partie \"Le montage\"",
        ],
        "doc_recap" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+recap'/Le+tournage+-+le+re%CC%81cap_090322.pdf",
        "fiche_recap_des_chapitres" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+recap'/Les+recap+-+Le+tournage+-+le+re%CC%81cap_090322_C.pdf",
        "boite_idees" => "",
        "to_do_list" => "",
        "exemple" => "",
        "chapitre_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+recap'/Le+chapitre+par+e%CC%81crit+-+Le+tournage+-+Le+Re%CC%81cap%E2%80%99.pdf",
        "tous_les_chapitres_par_ecrit" => "https://silence-2021.s3.eu-west-3.amazonaws.com/05+-+Tournage/Le+recap'/Le+chapitre+par+e%CC%81crit+-+Le+tournage+-+Tous+les+chapitres.pdf",
        "doc_a_completer" => "",
        "integration" => "",
        "commentaire" => ""
    ]
];
